export type PlateLocale = "en" | "mn"

export const plateCopy = {
  en: {
    language: "MN",
    nav: ["Foundations", "Components", "Workspaces", "Migration"],
    hero: {
      kicker: "UsionFlow theme direction / 01",
      lead: "A calmer, sharper",
      emphasis: "automation platform.",
      body: "A Tailwind design plate that translates Y Combinator’s editorial clarity into a practical interface system for UsionFlow.",
      version: "FORMIDABLE UI · v1.0",
      status: "READY FOR PILOT",
    },
    principles: {
      eyebrow: "Design principles",
      title: "Editorial clarity, built for serious work.",
      items: [
        ["Hierarchy before decoration", "Use scale, spacing, and type contrast before adding containers or effects."],
        ["One accent, clear meaning", "Orange marks the next important action. Status colors only communicate status."],
        ["Density without noise", "Keep operational screens compact, but separate groups with rhythm and hairline rules."],
      ],
    },
    foundations: {
      eyebrow: "01 / Foundations",
      title: "The visual source of truth.",
      body: "These values should replace one-off gradients, glass panels, radii, and competing accent colors across the platform.",
      palette: "Core palette",
      typography: "Typography",
      rhythm: "Shape & rhythm",
      display: "Editorial display",
      interface: "Interface and data",
      mono: "Technical labels",
      radius: "4px controls · 10px panels · full-pill actions",
      spacing: "4px base unit · generous 24/32px section gaps",
      depth: "Borders create depth; shadows are reserved for overlays",
    },
    components: {
      eyebrow: "02 / Components",
      title: "One component vocabulary.",
      body: "Every component currently used by UsionFlow is represented below in the new design language.",
      actions: "Actions",
      primary: "Create flow",
      secondary: "Preview",
      accent: "Ask AI",
      quiet: "Cancel",
      disabled: "Publishing",
      fields: "Fields",
      name: "Flow name",
      nameValue: "New customer welcome",
      channel: "Channel",
      channelValue: "Instagram",
      prompt: "AI instruction",
      promptValue: "Reply in the customer’s language and keep answers concise.",
      helper: "Saved automatically when you leave the field.",
      invalid: "A flow name is required.",
      feedback: "Status & feedback",
      ready: "Ready",
      review: "Needs review",
      failed: "Failed",
      draft: "Draft",
      successTitle: "Flow published",
      successBody: "The latest version is now serving customer messages.",
      menus: "Menus & selection",
      channelFilter: "Channel",
      channels: ["All channels", "Instagram", "Facebook", "Web chat"],
      moreActions: "More actions",
      menuItems: ["Duplicate", "Export report", "Archive", "Delete"],
      dateRange: "Date range",
      datePresets: ["Today", "7 days", "30 days", "This month"],
      clear: "Clear",
      apply: "Apply range",
      overlays: "Overlay patterns",
      openCreate: "Create flow",
      openDetails: "View details",
      openDelete: "Delete flow",
      createModal: {
        eyebrow: "New automation",
        title: "Create a flow",
        body: "Start from a proven pattern, then adapt the details to your customer journey.",
        name: "Flow name",
        nameValue: "Delivery status assistant",
        template: "Starting point",
        templates: ["Blank flow", "Customer welcome", "Order support"],
        channel: "Primary channel",
        description: "Internal note",
        descriptionValue: "Answers delivery questions and routes exceptions to the support team.",
        cancel: "Cancel",
        create: "Create flow",
      },
      detailsModal: {
        eyebrow: "Flow details",
        title: "Order support",
        body: "A focused side panel keeps context visible while operators review ownership, reach, and recent activity.",
        labels: ["Status", "Owner", "Channels", "Last published"],
        values: ["Live", "AI assistant", "Instagram, Web chat", "Today, 10:42"],
        action: "Open in builder",
      },
      deleteModal: {
        eyebrow: "Destructive action",
        title: "Delete Order support?",
        body: "This removes the flow and its draft history. Published conversations will remain in the inbox.",
        cancel: "Keep flow",
        confirm: "Delete flow",
      },
      inventory: {
        title: "Current UsionFlow inventory",
        inUse: "In use",
        identity: "Identity & feedback",
        people: ["Naraa", "AI assistant", "Customer"],
        online: "Online",
        tooltip: "Assign conversation",
        showToast: "Show toast",
        toastTitle: "Changes saved",
        toastBody: "The flow is ready to test.",
        loading: "Loading & progress",
        progress: "72% processed",
        skeleton: "Loading conversation",
        controls: "Time & values",
        time: "Appointment time",
        confidence: "AI confidence",
        messages: "Message limit",
        currency: "Minimum order",
        decrease: "Decrease value",
        increase: "Increase value",
        disclosure: "Collapsible controls",
        advanced: "Advanced settings",
        advancedValue: "Retry 2 times · Timeout 30s",
        media: "Media inputs",
        image: "Image",
        multiImage: "Multi-image",
        file: "File",
        chooseFile: "Choose file",
        addImage: "Add image",
        fileName: "brand-guide.pdf",
        flowFields: "Flow input types",
        quickReplies: "Quick replies",
        replies: ["Track order", "Change address", "Talk to support"],
        buttonTemplate: "Button template",
        message: "Your order is on the way.",
        track: "Track order",
        dictionary: "Dictionary",
        dictionaryRows: [["language", "mn"], ["priority", "normal"]],
        dynamicOutputs: "Dynamic outputs",
        outputs: ["paid", "pending", "failed"],
        knowledge: "Business knowledge",
        knowledgeValue: "Returns policy · Product catalog",
        code: "Code editor",
        codeValue: "return { status: 'ready' }",
        carousel: "Carousel template",
        products: [["AI Starter kit", "₮ 89,000"], ["Commerce flow", "₮ 129,000"]],
      },
    },
    workspaces: {
      eyebrow: "03 / Product patterns",
      title: "The theme inside UsionFlow.",
      body: "These five high-impact surfaces show how one shared shell can support conversations, building, reporting, operations, and commerce settings.",
      tabs: ["Inbox", "Flow builder", "Analytics", "Back office", "Shop settings"],
      workspace: "Workspace",
      search: "Search",
      navigation: ["Overview", "Inbox", "Flows", "Shop", "Analytics"],
      inbox: {
        title: "Unified inbox",
        count: "12 open",
        conversations: [
          ["Ariunaa", "Can I change the delivery address?", "2m"],
          ["Temuulen", "Thank you — that worked.", "18m"],
          ["Nomin", "Is the black option still available?", "1h"],
        ],
        customer: "Ariunaa",
        source: "Instagram · Open",
        incoming: "Can I change the delivery address before it ships?",
        reply: "Of course. Please send the new district and address, and I’ll update the order.",
        placeholder: "Write a reply…",
        details: "Conversation details",
        assigned: "Assigned to",
        owner: "AI assistant",
        category: "Category",
        categoryValue: "Orders",
      },
      builder: {
        title: "Customer support router",
        saved: "Saved",
        live: "Live",
        test: "Test flow",
        preview: "Preview",
        publish: "Publish",
        published: "Published",
        aiAssistant: "Build with AI",
        undo: "Undo",
        redo: "Redo",
        libraryTitle: "Node library",
        librarySearch: "Search nodes…",
        libraryGroups: [
          ["Triggers", ["Instagram Trigger", "Keyword match"]],
          ["AI & logic", ["MongolGPT Tools", "Equal router"]],
          ["Business tools", ["IG Send Message", "Human Assignment", "Shop Tools"]],
        ],
        canvasLabel: "Customer support · version 12",
        nodes: [
          { kind: "Instagram", title: "Instagram Trigger", body: "Starts on every new direct message.", details: [["Account", "@usion.shop"], ["Output", "Instagram message"]], output: "message" },
          { kind: "AI", title: "MongolGPT Tools", body: "Answers from business knowledge with connected tools.", details: [["Model", "Model-4"], ["Tools", "Shop · Booking"]], output: "confidence" },
          { kind: "Logic", title: "Equal router", body: "Routes the answer using a confidence option.", details: [["Option", "Score ≥ 80%"], ["No match", "Human team"]], output: "result" },
          { kind: "Instagram", title: "IG Send Message", body: "Sends the generated response to the customer.", details: [["Input", "AI output"], ["Fallback", "Message text"]], output: "sent" },
          { kind: "Handoff", title: "Human Assignment", body: "Hands the full conversation to customer care.", details: [["Assigned to", "Human assistant"], ["Priority", "Normal"]], output: "assigned" },
        ],
        branches: ["PASS", "REVIEW"],
        inspectorEyebrow: "Selected node",
        inspectorTitle: "Configuration",
        inspectorBody: "Changes save automatically and stay scoped to this flow version.",
        nodeName: "Node name",
        advanced: "Advanced settings",
        saveNode: "Save node",
        testPanelTitle: "Test run",
        testPanelBody: "All 5 steps completed in 1.8s",
        testSteps: ["Instagram message received", "Knowledge answer generated", "Confidence 94% · pass", "Reply sent"],
        close: "Close",
        minimap: "Minimap",
      },
      analytics: {
        title: "Performance",
        period: "Last 30 days",
        channel: "All channels",
        export: "Export",
        metrics: [["Conversations", "3,284", "+18%"], ["Resolved by AI", "71%", "+6%"], ["Median reply", "9s", "−2s"]],
        chart: "Conversation volume",
        sources: "Channel performance",
        table: [["Instagram", "1,842", "74%"], ["Facebook", "926", "68%"], ["Web chat", "516", "72%"]],
      },
      backOffice: {
        eyebrow: "Back office",
        title: "Operations",
        body: "Manage customer work, automation health, and ownership from one dense but calm surface.",
        create: "Create flow",
        search: "Search flows…",
        searchLabel: "Search flows",
        status: "Status",
        statuses: ["All statuses", "Live", "Needs review", "Draft"],
        date: "Sep 1–30",
        tableLabel: "Automation flows",
        columns: ["Flow", "Channel", "Status", "Owner", "Runs", "Updated", ""],
        rows: [
          ["Order support", "Instagram", "Live", "AI assistant", "1,284", "2m ago"],
          ["New customer welcome", "Web chat", "Live", "Naraa", "846", "18m ago"],
          ["Delivery follow-up", "Facebook", "Needs review", "Temuulen", "312", "1h ago"],
          ["Product finder", "Instagram", "Draft", "Unassigned", "—", "Yesterday"],
        ],
        selected: "flows selected",
        bulkEdit: "Change owner",
        showing: "Showing 1–4 of 18 flows",
        previous: "Previous",
        next: "Next",
        rowActions: ["View details", "Duplicate", "Archive", "Delete"],
      },
      shopSettings: {
        eyebrow: "Commerce",
        title: "Shop settings",
        body: "Manage the customer-facing store, checkout, and fulfillment rules from one place.",
        saved: "All changes saved",
        viewStore: "View store",
        publish: "Publish changes",
        published: "Published",
        sections: ["Storefront", "Domain", "Payments", "Orders & delivery"],
        storefront: {
          title: "Storefront",
          body: "The name and description customers see at the top of your shop.",
          name: "Shop name",
          nameValue: "Usion Studio",
          description: "Shop description",
          descriptionValue: "Automation tools and practical templates for growing teams.",
          address: "Store address",
          addressValue: "Sukhbaatar district, Ulaanbaatar",
          preview: "Live storefront",
          url: "usion-studio.usion.shop",
          visibility: "Store visibility",
          visibilityBody: "Customers can browse products and place orders.",
          accent: "Store accent",
        },
        domain: {
          title: "Domain",
          body: "Use the free Usion address or connect a domain your customers already know.",
          generated: "Usion shop address",
          copy: "Copy",
          copied: "Copied",
          custom: "Custom domain",
          customValue: "shop.usionstudio.mn",
          connect: "Connect domain",
          pending: "DNS verification pending",
          instruction: "Add an A record for shop pointing to 76.76.21.21. We will verify it automatically.",
        },
        payments: {
          title: "Payments",
          body: "Choose how customers pay and where completed payments settle.",
          qpay: "QPay merchant",
          connected: "Connected",
          merchant: "Usion Studio LLC · 99112233",
          mode: "Payment collection",
          modes: ["Full payment", "Advance payment", "Pay on delivery"],
          account: "Settlement account",
          accounts: ["Khan Bank · •• 4821", "Golomt Bank · •• 9034"],
          invoice: "Invoice expiry",
          invoiceValue: "30 minutes",
        },
        orders: {
          title: "Orders & delivery",
          body: "Set the purchasing and fulfillment options available at checkout.",
          options: [
            ["Accept online orders", "Allow customers to complete checkout from the storefront."],
            ["Delivery", "Collect a delivery address and delivery note."],
            ["Store pickup", "Let customers collect prepared orders in person."],
            ["Allow pre-orders", "Accept quantities above the currently available balance."],
          ],
          currency: "Store currency",
          currencies: ["MNT — Mongolian tögrög", "USD — US dollar"],
          minimum: "Minimum order",
          minimumValue: "₮ 20,000",
          leadTime: "Preparation time",
          leadTimes: ["Same day", "1 business day", "2–3 business days"],
        },
      },
    },
    states: {
      eyebrow: "04 / System states",
      title: "Quiet when idle. Obvious when action is needed.",
      empty: ["Empty", "No flows yet", "Start with one customer moment and build from there.", "Create first flow"],
      loading: ["Loading", "Syncing conversations", "Keep the layout stable while fresh messages arrive."],
      error: ["Error", "Connection needs attention", "Instagram stopped syncing 8 minutes ago.", "Reconnect"],
    },
    migration: {
      eyebrow: "05 / Migration map",
      title: "How the current platform changes.",
      body: "Roll out by shared primitives first, then migrate one complete workspace at a time. Avoid mixing old and new treatments inside the same surface.",
      headers: ["Current pattern", "New rule", "Why"],
      rows: [
        ["Blue-purple gradients", "Warm paper canvas", "Reduces visual fatigue and gives content the hierarchy."],
        ["Translucent glass cards", "Solid surfaces + hairline borders", "Keeps dense screens crisp and predictable."],
        ["Many decorative accents", "Orange for primary intent", "Makes the next action unmistakable."],
        ["Rounded cards everywhere", "Purposeful 4 / 10 / pill radius", "Restores structure and visual rhythm."],
        ["Uniform sans-serif hierarchy", "Serif display + sans interface", "Separates narrative context from operational controls."],
      ],
      phase: "Recommended rollout",
      phases: [["01", "Tokens + shared controls"], ["02", "Navigation + page shells"], ["03", "Inbox + flow editor"], ["04", "Reporting + commerce"]],
    },
    footer: {
      label: "UsionFlow / Formidable UI",
      title: "Build the system once. Let every product surface inherit it.",
      note: "Reference plate · Tailwind implementation · English and Mongolian ready",
    },
  },
  mn: {
    language: "EN",
    nav: ["Суурь", "Компонент", "Ажлын орчин", "Шилжилт"],
    hero: {
      kicker: "UsionFlow theme чиглэл / 01",
      lead: "Илүү тайван, илүү хурц",
      emphasis: "автоматжуулалтын платформ.",
      body: "Y Combinator-ийн редакцын тод байдлыг UsionFlow-д ашиглах практик интерфэйсийн систем болгосон Tailwind дизайны хавтан.",
      version: "FORMIDABLE UI · v1.0",
      status: "ТУРШИЛТАД БЭЛЭН",
    },
    principles: {
      eyebrow: "Дизайны зарчим",
      title: "Ноцтой ажилд зориулсан редакцын тод байдал.",
      items: [
        ["Чимэглэлээс өмнө эрэмбэ", "Сав, эффект нэмэхээс өмнө хэмжээ, зай, үсгийн ялгаагаар утгаа гарга."],
        ["Нэг акцент, тод утга", "Улбар шар дараагийн чухал үйлдлийг заана. Төлөвийн өнгө зөвхөн төлөв илэрхийлнэ."],
        ["Шуугиангүй нягтрал", "Үйл ажиллагааны дэлгэцийг нягт байлгаж, бүлгүүдийг зай ба нарийн зураасаар салгана."],
      ],
    },
    foundations: {
      eyebrow: "01 / Суурь",
      title: "Визуалын нэг эх сурвалж.",
      body: "Эдгээр утга платформ даяарх тус тусын градиент, шилэн самбар, радиус, өрсөлдсөн акцент өнгийг орлоно.",
      palette: "Үндсэн өнгө",
      typography: "Үсгийн систем",
      rhythm: "Хэлбэр ба хэмнэл",
      display: "Редакцын гарчиг",
      interface: "Интерфэйс ба өгөгдөл",
      mono: "Техникийн шошго",
      radius: "4px удирдлага · 10px самбар · pill үндсэн үйлдэл",
      spacing: "4px суурь нэгж · 24/32px бүлгийн зай",
      depth: "Гүнийг хүрээгээр гаргана; сүүдэр зөвхөн давхар цонхонд",
    },
    components: {
      eyebrow: "02 / Компонент",
      title: "Нэг компонентын хэл.",
      body: "UsionFlow-д одоо ашиглаж буй компонент бүрийг шинэ дизайны хэлээр доор харуулав.",
      actions: "Үйлдэл",
      primary: "Flow үүсгэх",
      secondary: "Урьдчилан харах",
      accent: "AI-аас асуух",
      quiet: "Цуцлах",
      disabled: "Нийтэлж байна",
      fields: "Талбар",
      name: "Flow-ийн нэр",
      nameValue: "Шинэ хэрэглэгчийг угтах",
      channel: "Суваг",
      channelValue: "Instagram",
      prompt: "AI заавар",
      promptValue: "Хэрэглэгчийн хэлээр товч бөгөөд тод хариул.",
      helper: "Талбараас гарахад автоматаар хадгална.",
      invalid: "Flow-ийн нэр шаардлагатай.",
      feedback: "Төлөв ба мэдээлэл",
      ready: "Бэлэн",
      review: "Шалгах хэрэгтэй",
      failed: "Алдаа",
      draft: "Ноорог",
      successTitle: "Flow нийтлэгдлээ",
      successBody: "Хамгийн сүүлийн хувилбар хэрэглэгчийн мессежид ажиллаж байна.",
      menus: "Цэс ба сонголт",
      channelFilter: "Суваг",
      channels: ["Бүх суваг", "Instagram", "Facebook", "Вэб чат"],
      moreActions: "Бусад үйлдэл",
      menuItems: ["Хувилах", "Тайлан татах", "Архивлах", "Устгах"],
      dateRange: "Огнооны хүрээ",
      datePresets: ["Өнөөдөр", "7 хоног", "30 хоног", "Энэ сар"],
      clear: "Цэвэрлэх",
      apply: "Хүрээ сонгох",
      overlays: "Давхар цонхны загвар",
      openCreate: "Flow үүсгэх",
      openDetails: "Дэлгэрэнгүй харах",
      openDelete: "Flow устгах",
      createModal: {
        eyebrow: "Шинэ автоматжуулалт",
        title: "Flow үүсгэх",
        body: "Батлагдсан загвараас эхэлж, хэрэглэгчийн аялалдаа тохируулан дэлгэрүүлээрэй.",
        name: "Flow-ийн нэр",
        nameValue: "Хүргэлтийн төлөвийн туслах",
        template: "Эхлэх загвар",
        templates: ["Хоосон flow", "Хэрэглэгч угтах", "Захиалгын тусламж"],
        channel: "Үндсэн суваг",
        description: "Дотоод тэмдэглэл",
        descriptionValue: "Хүргэлтийн асуултад хариулж, онцгой тохиолдлыг тусламжийн багт шилжүүлнэ.",
        cancel: "Цуцлах",
        create: "Flow үүсгэх",
      },
      detailsModal: {
        eyebrow: "Flow-ийн мэдээлэл",
        title: "Захиалгын тусламж",
        body: "Төвлөрсөн хажуугийн самбар нь хариуцагч, хамрах хүрээ, сүүлийн үйлдлийг шалгах үед үндсэн ажлыг харагдуулна.",
        labels: ["Төлөв", "Хариуцагч", "Суваг", "Сүүлд нийтэлсэн"],
        values: ["Идэвхтэй", "AI туслах", "Instagram, Вэб чат", "Өнөөдөр, 10:42"],
        action: "Builder-д нээх",
      },
      deleteModal: {
        eyebrow: "Буцаах боломжгүй үйлдэл",
        title: "Захиалгын тусламжийг устгах уу?",
        body: "Flow болон ноорог түүх устна. Нийтлэгдсэн харилцан яриа inbox-д хэвээр үлдэнэ.",
        cancel: "Flow-г хадгалах",
        confirm: "Flow устгах",
      },
      inventory: {
        title: "UsionFlow-д одоо ашиглаж буй компонентууд",
        inUse: "Ашиглаж буй",
        identity: "Хэрэглэгч ба мэдээлэл",
        people: ["Нараа", "AI туслах", "Хэрэглэгч"],
        online: "Онлайн",
        tooltip: "Харилцан яриа хуваарилах",
        showToast: "Мэдэгдэл харуулах",
        toastTitle: "Өөрчлөлт хадгалагдлаа",
        toastBody: "Flow туршихад бэлэн.",
        loading: "Ачаалалт ба явц",
        progress: "72% боловсруулсан",
        skeleton: "Харилцан яриа ачаалж байна",
        controls: "Цаг ба утга",
        time: "Уулзалтын цаг",
        confidence: "AI итгэлцэл",
        messages: "Мессежийн хязгаар",
        currency: "Доод захиалга",
        decrease: "Утга хасах",
        increase: "Утга нэмэх",
        disclosure: "Задардаг удирдлага",
        advanced: "Нарийвчилсан тохиргоо",
        advancedValue: "2 удаа дахин оролдох · 30с хүлээх",
        media: "Медиа талбар",
        image: "Зураг",
        multiImage: "Олон зураг",
        file: "Файл",
        chooseFile: "Файл сонгох",
        addImage: "Зураг нэмэх",
        fileName: "brand-guide.pdf",
        flowFields: "Flow талбарын төрлүүд",
        quickReplies: "Түргэн хариулт",
        replies: ["Захиалга хянах", "Хаяг солих", "Тусламжтай холбогдох"],
        buttonTemplate: "Товчлуурын загвар",
        message: "Таны захиалга хүргэлтэд гарлаа.",
        track: "Захиалга хянах",
        dictionary: "Толь бичиг",
        dictionaryRows: [["language", "mn"], ["priority", "normal"]],
        dynamicOutputs: "Динамик гаралт",
        outputs: ["paid", "pending", "failed"],
        knowledge: "Бизнесийн мэдлэг",
        knowledgeValue: "Буцаалтын журам · Барааны каталог",
        code: "Код засварлагч",
        codeValue: "return { status: 'ready' }",
        carousel: "Карусел загвар",
        products: [["AI эхлэх багц", "₮ 89,000"], ["Худалдааны flow", "₮ 129,000"]],
      },
    },
    workspaces: {
      eyebrow: "03 / Бүтээгдэхүүний загвар",
      title: "UsionFlow доторх шинэ theme.",
      body: "Эдгээр таван өндөр нөлөөтэй дэлгэц нь нэг shell-ээр харилцан яриа, flow бүтээлт, тайлан, үйл ажиллагаа, худалдааны тохиргоог хэрхэн дэмжихийг харуулна.",
      tabs: ["Inbox", "Flow builder", "Аналитик", "Back office", "Дэлгүүрийн тохиргоо"],
      workspace: "Ажлын орчин",
      search: "Хайх",
      navigation: ["Ерөнхий", "Inbox", "Flows", "Дэлгүүр", "Аналитик"],
      inbox: {
        title: "Нэгдсэн inbox",
        count: "12 нээлттэй",
        conversations: [["Ариунаа", "Хүргэлтийн хаягаа сольж болох уу?", "2м"], ["Тэмүүлэн", "Баярлалаа — боллоо.", "18м"], ["Номин", "Хар өнгө үлдсэн үү?", "1ц"]],
        customer: "Ариунаа",
        source: "Instagram · Нээлттэй",
        incoming: "Илгээхээс нь өмнө хүргэлтийн хаягаа сольж болох уу?",
        reply: "Бололгүй яах вэ. Шинэ дүүрэг, хаягаа явуулбал захиалгыг шинэчилж өгье.",
        placeholder: "Хариу бичих…",
        details: "Харилцан ярианы мэдээлэл",
        assigned: "Хариуцагч",
        owner: "AI туслах",
        category: "Ангилал",
        categoryValue: "Захиалга",
      },
      builder: {
        title: "Хэрэглэгчийн тусламж хуваарилах",
        saved: "Хадгалсан",
        live: "Идэвхтэй",
        test: "Flow турших",
        preview: "Урьдчилан харах",
        publish: "Нийтлэх",
        published: "Нийтэлсэн",
        aiAssistant: "AI-аар бүтээх",
        undo: "Буцаах",
        redo: "Дахих",
        libraryTitle: "Node сан",
        librarySearch: "Node хайх…",
        libraryGroups: [
          ["Эхлүүлэгч", ["Instagram Trigger", "Түлхүүр үг"]],
          ["AI ба логик", ["MongolGPT Tools", "Equal router"]],
          ["Бизнес хэрэгсэл", ["IG Send Message", "Human Assignment", "Shop Tools"]],
        ],
        canvasLabel: "Хэрэглэгчийн тусламж · хувилбар 12",
        nodes: [
          { kind: "Instagram", title: "Instagram Trigger", body: "Шинэ шууд мессеж бүр дээр эхэлнэ.", details: [["Бүртгэл", "@usion.shop"], ["Гаралт", "Instagram message"]], output: "message" },
          { kind: "AI", title: "MongolGPT Tools", body: "Бизнесийн мэдлэг болон холбогдсон хэрэгслээр хариулна.", details: [["Модел", "Model-4"], ["Хэрэгсэл", "Shop · Booking"]], output: "confidence" },
          { kind: "Логик", title: "Equal router", body: "Итгэлцлийн сонголтоор хариуг чиглүүлнэ.", details: [["Сонголт", "Оноо ≥ 80%"], ["Таарахгүй", "Хүний баг"]], output: "result" },
          { kind: "Instagram", title: "IG Send Message", body: "Үүссэн хариултыг хэрэглэгчид илгээнэ.", details: [["Оролт", "AI output"], ["Нөөц", "Message text"]], output: "sent" },
          { kind: "Handoff", title: "Human Assignment", body: "Бүрэн харилцан яриаг тусламжийн багт шилжүүлнэ.", details: [["Хариуцагч", "Human assistant"], ["Зэрэг", "Энгийн"]], output: "assigned" },
        ],
        branches: ["ДАВАХ", "ШАЛГАХ"],
        inspectorEyebrow: "Сонгосон node",
        inspectorTitle: "Тохиргоо",
        inspectorBody: "Өөрчлөлт автоматаар хадгалагдаж, энэ flow хувилбарт хамаарна.",
        nodeName: "Node-ийн нэр",
        advanced: "Нарийвчилсан тохиргоо",
        saveNode: "Node хадгалах",
        testPanelTitle: "Туршилтын үр дүн",
        testPanelBody: "5 алхам 1.8 секундэд амжилттай дууслаа",
        testSteps: ["Instagram мессеж хүлээн авсан", "Мэдлэгийн хариулт үүссэн", "Итгэлцэл 94% · давсан", "Хариу илгээгдсэн"],
        close: "Хаах",
        minimap: "Жижиг зураг",
      },
      analytics: {
        title: "Гүйцэтгэл",
        period: "Сүүлийн 30 хоног",
        channel: "Бүх суваг",
        export: "Татах",
        metrics: [["Харилцан яриа", "3,284", "+18%"], ["AI шийдсэн", "71%", "+6%"], ["Дундаж хариу", "9с", "−2с"]],
        chart: "Харилцан ярианы хэмжээ",
        sources: "Сувгийн гүйцэтгэл",
        table: [["Instagram", "1,842", "74%"], ["Facebook", "926", "68%"], ["Вэб чат", "516", "72%"]],
      },
      backOffice: {
        eyebrow: "Back office",
        title: "Үйл ажиллагаа",
        body: "Хэрэглэгчийн ажил, автоматжуулалтын төлөв, хариуцагчдыг нэг нягт боловч тайван дэлгэцээс удирдана.",
        create: "Flow үүсгэх",
        search: "Flow хайх…",
        searchLabel: "Flow хайх",
        status: "Төлөв",
        statuses: ["Бүх төлөв", "Идэвхтэй", "Шалгах хэрэгтэй", "Ноорог"],
        date: "9-р сар 1–30",
        tableLabel: "Автоматжуулалтын flow-ууд",
        columns: ["Flow", "Суваг", "Төлөв", "Хариуцагч", "Ажилласан", "Шинэчилсэн", ""],
        rows: [
          ["Захиалгын тусламж", "Instagram", "Идэвхтэй", "AI туслах", "1,284", "2м өмнө"],
          ["Шинэ хэрэглэгч угтах", "Вэб чат", "Идэвхтэй", "Нараа", "846", "18м өмнө"],
          ["Хүргэлтийн дараах холбоо", "Facebook", "Шалгах хэрэгтэй", "Тэмүүлэн", "312", "1ц өмнө"],
          ["Бүтээгдэхүүн сонгогч", "Instagram", "Ноорог", "Оноогоогүй", "—", "Өчигдөр"],
        ],
        selected: "flow сонгосон",
        bulkEdit: "Хариуцагч солих",
        showing: "18 flow-оос 1–4-г харуулж байна",
        previous: "Өмнөх",
        next: "Дараах",
        rowActions: ["Дэлгэрэнгүй харах", "Хувилах", "Архивлах", "Устгах"],
      },
      shopSettings: {
        eyebrow: "Худалдаа",
        title: "Дэлгүүрийн тохиргоо",
        body: "Хэрэглэгчийн дэлгүүр, төлбөр, хүргэлтийн дүрмийг нэг газраас удирдана.",
        saved: "Бүх өөрчлөлт хадгалагдсан",
        viewStore: "Дэлгүүр харах",
        publish: "Өөрчлөлт нийтлэх",
        published: "Нийтэлсэн",
        sections: ["Дэлгүүр", "Домэйн", "Төлбөр", "Захиалга ба хүргэлт"],
        storefront: {
          title: "Дэлгүүр",
          body: "Дэлгүүрийн эхэнд хэрэглэгчдэд харагдах нэр болон тайлбар.",
          name: "Дэлгүүрийн нэр",
          nameValue: "Usion Studio",
          description: "Дэлгүүрийн тайлбар",
          descriptionValue: "Өсөж буй багуудад зориулсан автоматжуулалтын хэрэгсэл, практик загварууд.",
          address: "Дэлгүүрийн хаяг",
          addressValue: "Сүхбаатар дүүрэг, Улаанбаатар",
          preview: "Идэвхтэй дэлгүүр",
          url: "usion-studio.usion.shop",
          visibility: "Дэлгүүрийн харагдац",
          visibilityBody: "Хэрэглэгч бараа үзэж, захиалга өгөх боломжтой.",
          accent: "Дэлгүүрийн акцент",
        },
        domain: {
          title: "Домэйн",
          body: "Үнэгүй Usion хаяг ашиглах эсвэл хэрэглэгчдийн мэддэг домэйныг холбоно.",
          generated: "Usion дэлгүүрийн хаяг",
          copy: "Хуулах",
          copied: "Хуулсан",
          custom: "Тусгай домэйн",
          customValue: "shop.usionstudio.mn",
          connect: "Домэйн холбох",
          pending: "DNS баталгаажуулалт хүлээгдэж байна",
          instruction: "shop хостыг 76.76.21.21 рүү заасан A record нэмнэ үү. Бид автоматаар шалгана.",
        },
        payments: {
          title: "Төлбөр",
          body: "Хэрэглэгч хэрхэн төлөх болон төлбөр аль дансанд орохыг сонгоно.",
          qpay: "QPay мерчант",
          connected: "Холбогдсон",
          merchant: "Usion Studio ХХК · 99112233",
          mode: "Төлбөр авах хэлбэр",
          modes: ["Бүрэн төлбөр", "Урьдчилгаа төлбөр", "Хүлээн авахдаа төлөх"],
          account: "Орлого хүлээн авах данс",
          accounts: ["Хаан банк · •• 4821", "Голомт банк · •• 9034"],
          invoice: "Нэхэмжлэхийн хугацаа",
          invoiceValue: "30 минут",
        },
        orders: {
          title: "Захиалга ба хүргэлт",
          body: "Checkout дээр харагдах худалдан авалт, хүлээлгэн өгөх сонголтыг тохируулна.",
          options: [
            ["Онлайн захиалга авах", "Хэрэглэгч дэлгүүрээс checkout дуусгах боломжтой."],
            ["Хүргэлт", "Хүргэлтийн хаяг болон тэмдэглэл авна."],
            ["Дэлгүүрээс авах", "Бэлэн захиалгыг өөрийн биеэр авах боломж өгнө."],
            ["Урьдчилсан захиалга зөвшөөрөх", "Үлдэгдлээс их тоо хэмжээг захиалах боломжтой."],
          ],
          currency: "Дэлгүүрийн валют",
          currencies: ["MNT — Монгол төгрөг", "USD — Америк доллар"],
          minimum: "Захиалгын доод дүн",
          minimumValue: "₮ 20,000",
          leadTime: "Бэлтгэх хугацаа",
          leadTimes: ["Өнөөдөртөө", "Ажлын 1 өдөр", "Ажлын 2–3 өдөр"],
        },
      },
    },
    states: {
      eyebrow: "04 / Системийн төлөв",
      title: "Тайван үедээ нам. Үйлдэл хэрэгтэй үедээ тод.",
      empty: ["Хоосон", "Flow алга байна", "Нэг хэрэглэгчийн мөчөөс эхэлж цааш нь бүтээ.", "Эхний flow үүсгэх"],
      loading: ["Уншиж байна", "Харилцан яриаг шинэчилж байна", "Шинэ мессеж ирэхэд layout-ийг тогтвортой байлгана."],
      error: ["Алдаа", "Холболт анхаарал шаардаж байна", "Instagram 8 минутын өмнө синк хийхээ зогсоосон.", "Дахин холбох"],
    },
    migration: {
      eyebrow: "05 / Шилжилтийн зураглал",
      title: "Одоогийн платформ хэрхэн өөрчлөгдөх вэ.",
      body: "Эхлээд shared primitive-үүдийг нэвтрүүлж, дараа нь нэг бүтэн ажлын орчныг үе шаттай шинэчилнэ. Нэг дэлгэцэд хуучин, шинэ хэллэгийг бүү холь.",
      headers: ["Одоогийн загвар", "Шинэ дүрэм", "Шалтгаан"],
      rows: [
        ["Цэнхэр-ягаан градиент", "Дулаан цаасан canvas", "Нүдний ачааллыг бууруулж, контентод эрэмбэ өгнө."],
        ["Тунгалаг шилэн card", "Цул surface + нарийн хүрээ", "Нягт дэлгэцийг цэвэр, тогтвортой болгоно."],
        ["Олон чимэглэлийн accent", "Үндсэн зорилгод улбар шар", "Дараагийн үйлдлийг маргаангүй болгоно."],
        ["Бүх зүйл дугуй card", "Зориулалттай 4 / 10 / pill radius", "Бүтэц болон хэмнэлийг буцаана."],
        ["Нэгэн хэвийн sans эрэмбэ", "Serif гарчиг + sans интерфэйс", "Өгүүлэмж ба үйлдлийн удирдлагыг ялгана."],
      ],
      phase: "Санал болгох нэвтрүүлэлт",
      phases: [["01", "Token + shared control"], ["02", "Navigation + page shell"], ["03", "Inbox + flow editor"], ["04", "Тайлан + commerce"]],
    },
    footer: {
      label: "UsionFlow / Formidable UI",
      title: "Системийг нэг удаа бүтээ. Бүтээгдэхүүний бүх дэлгэц түүнийг өвлөг.",
      note: "Reference plate · Tailwind implementation · English, Монгол хэлтэй",
    },
  },
} as const
